/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlIcon: typeof import('./../components/AlIcon/index.vue')['default']
    Auth: typeof import('./../components/Auth/index.vue')['default']
    AuthAll: typeof import('./../components/AuthAll/index.vue')['default']
    Copyright: typeof import('./../components/Copyright/index.vue')['default']
    DefaultPage: typeof import('./../components/DefaultPage/index.vue')['default']
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    Filtrator: typeof import('./../components/Filtrator/index.vue')['default']
    FixedActionBar: typeof import('./../components/FixedActionBar/index.vue')['default']
    HintDialog: typeof import('./../components/HintDialog/index.vue')['default']
    ImagePreview: typeof import('./../components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./../components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
    LanguageSwitcher: typeof import('./../components/LanguageSwitcher/index.vue')['default']
    NotAllowed: typeof import('./../components/NotAllowed/index.vue')['default']
    PageHeader: typeof import('./../components/PageHeader/index.vue')['default']
    PageMain: typeof import('./../components/PageMain/index.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    PcasCascader: typeof import('./../components/PcasCascader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/SearchBar/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    SystemInfo: typeof import('./../components/SystemInfo/index.vue')['default']
    TableSkeleton: typeof import('./../components/TableSkeleton/index.vue')['default']
    Trend: typeof import('./../components/Trend/index.vue')['default']
  }
}

// For TSX support
declare global {
  const AlIcon: typeof import('./../components/AlIcon/index.vue')['default']
  const Auth: typeof import('./../components/Auth/index.vue')['default']
  const AuthAll: typeof import('./../components/AuthAll/index.vue')['default']
  const Copyright: typeof import('./../components/Copyright/index.vue')['default']
  const DefaultPage: typeof import('./../components/DefaultPage/index.vue')['default']
  const FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
  const Filtrator: typeof import('./../components/Filtrator/index.vue')['default']
  const FixedActionBar: typeof import('./../components/FixedActionBar/index.vue')['default']
  const HintDialog: typeof import('./../components/HintDialog/index.vue')['default']
  const ImagePreview: typeof import('./../components/ImagePreview/index.vue')['default']
  const ImagesUpload: typeof import('./../components/ImagesUpload/index.vue')['default']
  const ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
  const LanguageSwitcher: typeof import('./../components/LanguageSwitcher/index.vue')['default']
  const NotAllowed: typeof import('./../components/NotAllowed/index.vue')['default']
  const PageHeader: typeof import('./../components/PageHeader/index.vue')['default']
  const PageMain: typeof import('./../components/PageMain/index.vue')['default']
  const Pagination: typeof import('./../components/Pagination/index.vue')['default']
  const PcasCascader: typeof import('./../components/PcasCascader/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchBar: typeof import('./../components/SearchBar/index.vue')['default']
  const SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  const SystemInfo: typeof import('./../components/SystemInfo/index.vue')['default']
  const TableSkeleton: typeof import('./../components/TableSkeleton/index.vue')['default']
  const Trend: typeof import('./../components/Trend/index.vue')['default']
}