Store:
  Driver: mysql
  Host: mysql-dtm
  User: egoadmin
  Password: egoadmin
  Port: 3306
  Db: egoadmin_dtm

MicroService:
  Driver: dtm-driver-ego
  Target: etcd://etcd:2379/egoadmin-dtm
  EndPoint: dtm:36790

HttpPort: 36789
GrpcPort: 36790
