include:
  - compose/mysql.yml
  - compose/redis.yml
  - compose/etcd.yml
  - compose/dtm.yml
  - compose/minio.yml
  - compose/image-processor.yml
  - compose/meilisearch.yml
  - compose/jaeger.yml
  - compose/app.yml
