// Package idgen implements a high-throughput internal primary-key generator.
//
// IDs generated by this package are optimized for database locality and
// distributed uniqueness. They are not random and must not be treated as
// unguessable public identifiers. Use a separate random public ID, token, or
// code for invite links, share links, and other user-visible security surfaces.
package idgen
